server:  
    port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
zuul:
  prefix: /api
  routes:
    people-service: 
      path: /**
      serviceId: people-service
    user-service: 
      path: /**
      serviceId: user-service
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
    registerWithEureka: false
