server:
    port: 9191

spring:
    application:
        name: oauth-server-service
    jpa:
        database: MYSQL
        hibernate:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardIntl
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true    
    datasource:
        url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
        username: root
        password: 12345
        driver-class-name: com.mysql.jdbc.Driver
        initialization-mode: always

logging:
    lavel:
        org:
            hibernate:
                type: trace
